version: "3.3"
services: 
  artemis:
    image: olgabotnari/artemis:latest
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.5'
      placement:
        constraints: 
          - node.role == worker
    ports:
      - "5000:5000"
