version: "3.3"
services: 
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "wordpress"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "wordpress"
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.5'
      placement:
        constraints: 
          - node.role == worker

    ports:
      - "3306:3306"

  redis:
    image: redis
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.5'
      placement:
        constraints: 
          - node.role == worker
    ports:
      - "6379:6379"

  wordpress:
    image: wordpress:php7.4
    environment:
      WORDPRESS_DB_HOST: "mysql:3306"
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress 
      WORDPRESS_DB_NAME: wordpress 
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.5'
      placement:
        constraints: 
          - node.role == worker
    ports:
      - "80:80"

  visualizer:
    image: dockersamples/visualizer
    deploy:
      mode: global
      placement:
        constraints: 
          - node.role == manager
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"