env:
  repo: "https://github.com/farrukh90/artemis"

name: ContinuousDelivery
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3


      # Runs a set of commands using the runners shell
      - name: Clone a repo
        run: |
          git clone ${{ env.repo }}



      # Runs set of commands using the runners shell
      - name: Switch Branch
        working-directory: artemis
        run: |
          git checkout 2.0.0



      # # Runs set of commands using the runners shell
      # - name: Remove Old Images
      #   working-directory: artemis
      #   run: |
      #     docker image prune -af



      # Runs set of commands using the runners shell
      - name: Docker Build
        working-directory: artemis
        run: |
          docker image build -t artemis:2.0.0   .
          


      # Runs set of commands using the runners shell
      - name: Tag Image
        working-directory: artemis
        run: |
          docker image tag artemis:2.0.0 olgabotnari/artemis:2.0.0
          docker images 


      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      # Runs set of commands using the runners shell
      - name: Push Image
        run: |
          docker push olgabotnari/artemis:2.0.0 


          













