env:
  repo: "https://github.com/farrukh90/nodejs"
  app_version: "2.0.0"
  app_name: "nodejs"

name: ContinuousDeliveryNodeJS
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "non" ]
  pull_request:
    branches: [ "non" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3


      # Runs a set of commands using the runners shell
      - name: Clone a repo
        run: |
          git clone ${{ env.repo }}



      # Runs set of commands using the runners shell
      - name: Switch Branch
        working-directory: ${{ env.app_name }}
        run: |
          git checkout ${{ env.app_version }}



      # # Runs set of commands using the runners shell
      # - name: Remove Old Images
      #   working-directory: ${{ env.app_name }}
      #   run: |
      #     docker image prune -af



      # Runs set of commands using the runners shell
      - name: Docker Build
        working-directory: ${{ env.app_name }}
        run: |
          docker image build -t ${{ env.app_name }}:${{ env.app_version }}   .
          


      # Runs set of commands using the runners shell
      - name: Tag Image
        working-directory: ${{ env.app_name }}
        run: |
          docker image tag ${{ env.app_name }}:${{ env.app_version }} ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.app_name }}:${{ env.app_version }}
          docker images 


      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      # Runs set of commands using the runners shell
      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.app_name }}:${{ env.app_version }} 
















